Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	create_orthology_dictionaries
	1

[Thu Oct 15 16:48:41 2020]
rule create_orthology_dictionaries:
    input: data/orthology_anophelinae.tsv
    output: results/orthogroups.pickle, results/genes.pickle
    jobid: 0

Terminating processes on user request, this might take some time.
[Thu Oct 15 16:48:43 2020]
Error in rule create_orthology_dictionaries:
    jobid: 0
    output: results/orthogroups.pickle, results/genes.pickle

RuleException:
CalledProcessError in line 10 of /home/lruzzant/evol-feat-snakemake/workflow/Snakefile:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /home/lruzzant/evol-feat-snakemake/workflow/.snakemake/scripts/tmps5fbwvv4.create_orthology_dictionaries.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/home/lruzzant/evol-feat-snakemake/workflow/Snakefile", line 10, in __rule_create_orthology_dictionaries
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Removing output files of failed job create_orthology_dictionaries since they might be corrupted:
results/orthogroups.pickle, results/genes.pickle
Complete log: /home/lruzzant/evol-feat-snakemake/workflow/.snakemake/log/2020-10-15T164841.649231.snakemake.log
