Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	merge_features
	1	split_user_orthogroup_features
	3

[Mon Feb 15 18:06:48 2021]
checkpoint split_user_orthogroup_features:
    input: input/apoidea_og_feats.tsv
    output: output/user_orthogroup_features/
    jobid: 2
Downstream jobs will be updated after completion.

Updating job 1 (merge_features).
[Mon Feb 15 18:06:51 2021]
Finished job 2.
1 of 3 steps (33%) done

[Mon Feb 15 18:06:51 2021]
rule merge_features:
    input: output/user_orthogroup_features/ACN.tsv, output/user_orthogroup_features/AGE.tsv, output/user_orthogroup_features/CAF.tsv, output/user_orthogroup_features/CNV.tsv, output/user_orthogroup_features/CON.tsv, output/user_orthogroup_features/DUP.tsv, output/user_orthogroup_features/EVR.tsv, output/user_orthogroup_features/EXP.tsv, output/user_orthogroup_features/LCA.tsv, output/user_orthogroup_features/STA.tsv, output/user_orthogroup_features/UNI.tsv
    output: output/merged_orthogroup_features.tsv, output/merged_gene_features.tsv
    jobid: 3

[Mon Feb 15 18:06:52 2021]
Error in rule merge_features:
    jobid: 3
    output: output/merged_orthogroup_features.tsv, output/merged_gene_features.tsv

RuleException:
CalledProcessError in line 25 of /mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/merge_features.smk:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/scripts/tmpfsqvucn9.merge_features.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/merge_features.smk", line 25, in __rule_merge_features
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/log/2021-02-15T180648.287923.snakemake.log
