Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	merge_features
	1	split_user_orthogroup_features
	3

[Mon Feb 15 17:48:30 2021]
checkpoint split_user_orthogroup_features:
    input: input/apoidea_og_feats.tsv
    output: output/user_orthogroup_features/
    jobid: 2
Downstream jobs will be updated after completion.

[Mon Feb 15 17:48:30 2021]
Error in rule split_user_orthogroup_features:
    jobid: 2
    output: output/user_orthogroup_features/

RuleException:
URLError in line 32 of /mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/user_features.smk:
<urlopen error [Errno 2] No such file or directory: '/mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/scripts/split_orthogroup_features.py'>
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/user_features.smk", line 32, in __rule_split_user_orthogroup_features
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 222, in urlopen
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 525, in open
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 543, in _open
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 503, in _call_chain
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 1451, in file_open
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 1490, in open_local_file
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Removing output files of failed job split_user_orthogroup_features since they might be corrupted:
output/user_orthogroup_features/
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/log/2021-02-15T174830.435424.snakemake.log
